### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by YijinWen** [jmmorato/openddsharp#15]
Hello all,
I try to build a application with openddsharp.
The Application works like：
Publisher publishing topics data period. More than one Subscribers receive the topics data.

At the beginning the Subscribers runs well ,  after a while one of subscribers crash.

The application build on x64 windows.
In visual studio set debug mode, x64. 

The Windows Error Log:
![image](https://user-images.githubusercontent.com/22764341/62258210-f9e33d00-b43b-11e9-8994-d2074b0b7805.png)

Besides，I find duplicate messages received by subscribers.

Any pointers are much appreciated.

Thanks!

The test demo attached.
[TestDemo.zip](https://github.com/jmmorato/openddsharp/files/3453183/TestDemo.zip)

**Comment by jmmorato** [comment]
Hi YiJinWen,

Sorry for the late response, holidays time... ;)

I took a quick look to your TestDemo project. 

I would say that what your software consider duplicates is caused by a race condition on your `Publish(byte[] bytes, bool fragment = false)` method. You have a mutex on ` Publish(Message Message)` but the method call by the timers is not that one. Using a lock around the `Publish(byte[] bytes, bool fragment = false)` should solve the situation.

About the subscribers crash issue, I'm able to reproduce it. It seems there is an access violation exception when using the Take method on: 
https://github.com/objectcomputing/OpenDDS/blob/770d7a617304e91806d24cf0ffec90f9ac7a9160/dds/DCPS/DataReaderImpl_T.h#L1952

I will need more time to check the problem. Using the Read method doesn't seems to crash the application.

`_dataReader.Read(receivedData, sampleInfos, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateKind.NotReadSampleState, ViewStateMask.AnyViewState, InstanceStateKind.AliveInstanceState)`

Thanks for reporting and for the reproducer project. 

Attached the my first modifications.

[TestDemo_Modified.zip](https://github.com/jmmorato/openddsharp/files/3471315/TestDemo_Modified.zip)

PS: Better use another logging mechanism than the Console.WriteLine. All those WriteLine are impacting the performance of your application and they are locking on the WaitSet thread (not a good idea). Try a counter for the successfully received samples and print a summary at the end of the test or periodically in another thread.

**Comment by YijinWen** [comment]
Hello Jmmorato:
     Thank your response.

     I use your modified code do some test. I find use Read method the topic data may not period received.

    The publisher:
 
![image](https://user-images.githubusercontent.com/22764341/62592061-5515a380-b904-11e9-9353-6fa6a3dbd756.png)

    The subscriber:

![image](https://user-images.githubusercontent.com/22764341/62592086-6a8acd80-b904-11e9-92b3-5f1d6757db08.png)

    For quick test, I use Console.WriteLine. I will looking for other way to log.
