### ISSUE TITLE
Unresolved external symbols when building IDL

### ISSUE THREAD

**Issue by ethanshattuck** [jmmorato/openddsharp#16]
I have an IDL file containing 16 defined data types. When I build the IDL, I get unresolved external symbols.  It finally built successfully when my IDL only contained 15 data types. It's also important to mention that it didn't matter which data type was commented out. Is there a limit to IDL data types?
[ProblematicIDL.txt](https://github.com/jmmorato/openddsharp/files/3506230/ProblematicIDL.txt)

**Comment by jmmorato** [comment]
There is not limit on the IDL structures, but there is a limit in the number of sections allowed in the obj files: https://docs.microsoft.com/en-us/cpp/build/reference/bigobj-increase-number-of-sections-in-dot-obj-file?view=vs-2019

Replace the attached project file on your Idlgenerator downloaded package folder and the problem should be fixed: `.nuget\packages\openddsharp.idlgenerator\0.4.1\tools\native_project_tempate`

I will include the modification on next version.

[NativeIdlProject.zip](https://github.com/jmmorato/openddsharp/files/3506347/NativeIdlProject.zip)
(unzip the file and copy the vcxproj)

**Comment by ethanshattuck** [comment]
Thanks for the quick response. I compared my vcxproj with the one you supplied and they are the same... Did you send the wrong file? Also, I'm not sure how to navigate into the "native_project_template" file you spoke of. Thanks for the help!

**Comment by jmmorato** [comment]
Yep, perhaps my answer was not detailed enough.

The OpenDDSharp IDL generator first compiles the native C++ OpenDDS internally, based on a Visual Studio project template provided on the nuget package. The compilation of the C++ project is failing because the obj sections as explained on my previous answer, therefore the C++/CLI project is failing as well because do not find the required native library.

To fix the problem, I need to modify the C++ project template. As a workaround for the current version I attached the modified C++ project template that will be included on next version. You need to manually replace it on the global nuget cache. If you are using the default nuget configuration your global nuget cache should be placed on `%userprofile%\.nuget\packages`, so you need to change the file under:
`%userprofile%\.nuget\packages\openddsharp.idlgenerator\0.4.1\tools\native_project_tempate`

After that, remove the bin and obj folders on your IDL project and build the project again.

**Comment by ethanshattuck** [comment]
This worked. Thank you!

**Comment by jmmorato** [comment]
Great!

Let me reopen the issue, so I remember to fix it in the next release.

Thanks again for your report.
