### ISSUE TITLE
Interoperability between C# and C++

### ISSUE THREAD

**Issue by ethanshattuck** [jmmorato/openddsharp#17]
To test the interoperability between OpenDDSharp and OpenDDS, I ran the DevGuideExamples/DCPS/Messenger_Publisher (OpenDDS) and the HelloWorldSubscriber (OpenDDSharp). To make them compatible, I modified HelloWorldSubscriber's IDL to match Messenger_Publisher and used the same rtps.ini file for both applications, but no connection was made. What else needs to be done for this to work? Thanks

**Comment by jmmorato** [comment]
It works for me...

These are the modifications I did to the HelloWorld solution:
- Unload project HelloWorldPublisher because is not needed for the PoC
- Compile the Messenger IDL content with the TestMessage project
```
module Messenger{

#pragma DCPS_DATA_TYPE "Messenger::Message"
#pragma DCPS_DATA_KEY "Messenger::Message subject_id"

  struct Message {
	string from;
	string subject;
	long subject_id;
	string text;
	long   count;
  };
};
```
- Modify the namespace in the HelloWorldSubscriber Program.cs to `using OpenDDSharp.Messenger;`
- Change the topic name to `"Movie Discussion List"`
- Modify the log writeline as `Console.WriteLine("{0}-{1}: {2}", receivedData[i].subject_id, receivedData[i].subject, receivedData[i].text);`
- Run OpenDDS publisher `publisher.exe -DCPSConfigFile rtps.ini`
- Run OpenDDSharp subscriber `HelloWorldSubscriber.exe -DCPSConfigFile rtps.ini`

Usually, the interoperability between DDS implementations is tested using the ShapeDemo. I have tested the interoperability successfully between OpenDDSharp<->OpenDDSharp, OpenDDSharp<->OpenDDS and OpenDDSharp<->RTI Connext using the ShapeDemo app.

**Comment by ethanshattuck** [comment]
It worked.. Not sure what was wrong before. Thank you!
