### ISSUE TITLE
Null Participant

### ISSUE THREAD

**Issue by Oles7** [jmmorato/openddsharp#171]
Doing the following to create a DomainParticipant.

Code builds, but at runtime the participant is null after trying to create it.

 ```
Ace.Init();
DomainParticipantFactory dpf = ParticipantService.Instance.GetDomainParticipantFactory("-DCPSConfigFile", "rtps.ini");
DomainParticipant participant = dpf.CreateParticipant(42);
```

**Comment by jmmorato** [comment]
You are trying to load the file from the same folder than your executable and surely is not found there due to the structure of the folders in the final Unity application.

Load from ini file is tricky, and more tricky when you plan to build multiplatform, that's why I always recommend to configure transports and discovery from code:

- Previouly answered: https://github.com/jmmorato/openddsharp/issues/165
- OpenDDSharp on Unity Discussion: https://github.com/jmmorato/openddsharp/discussions/153

Please, use the previous linked discussion to ask for help about Unity (no officially supported by OpenDDSharp yet)

**Comment by jmmorato** [comment]
Sorry, I just miss-read it as it is the usual answer about Unity xD

Could you increase verbosity and share the logs? 
`ParticipantService.Instance.GetDomainParticipantFactory("-DCPSConfigFile", "rtps.ini", "-DCPSDebugLevel", "10", "-ORBLogFile", "LogFile.log", "-ORBDebugLevel", "10");`

also, if possible, share your `rtps.ini` file

**Comment by Oles7** [comment]
The same fixed worked, sorry I just tired that and it fixed the problem. Thanks!!!
