### ISSUE TITLE
.NET Core version?

### ISSUE THREAD

**Issue by ieglandDRS** [jmmorato/openddsharp#18]
I'd like to use OpenDDSharp with a Universal Windows Platform (UWP) app. However, I am unable to create a references from the UWP app's project to a generated IDL project. From what I can tell, the problem is related to OpenDDSharp targeting .NET Framework instead of .NET Core.  I'm exploring the possibility of porting this to .NET Core. However, I've never done that before and I wanted to see what you thought of that before I got too far. Do you think it's feasible? If I did it, would you be interested in a Pull request?

**Comment by jmmorato** [comment]
OpenDDSharp is a C++/CLI wrapper over OpenDDS. 

It is already announced that [.NET Core will support C++/CLI](https://github.com/dotnet/coreclr/issues/18013) on version 3, but the support [won't be crossplatform](https://github.com/dotnet/coreclr/issues/659) (just Windows).

My idea for .NET Core support is to create a pinvoke wrapper instead of using C++/CLI. The proof of concept for that wrapper is on the `pinvoke` branch. On that branch, I'm able to send primitives, arrays, sequences... between two .NET Core applications but the DDS API is not completed (just the minimum methods needed to write and read) and the code generator is not even started (I coded manually the IDL wrapper as well).

Another problem to solve is the crossplatform support. Right now, OpenDDSharp only compiles OpenDDS for x86 and x64 devices. If you want to run it on another platform it will require to compile OpenDDS for that platform too.

Summarizing, yes I plan to support .NET Core in the future but right now I have not too much time for the project and I could not answer you when the support will be implemented. Pull request are always welcome, for the `master` branch or the `pinvoke` branch.

**Comment by ieglandDRS** [comment]
Thank you for your response.

My UWP app will only be used on desktop Windows 10, so if .NET Core will support C++/CLI in version 3, then maybe waiting for version 3 would be easier? It's certainly only a stopgap solution.

I think I'll investigate that option and the pinvoke one. I'll keep you posted.

Thank you for all the work you've done and continue to do for OpenDDSharp.
