### ISSUE TITLE
.NET Core 2.2 or 3.x support

### ISSUE THREAD

**Issue by Cingulara** [jmmorato/openddsharp#22]
I have a need to use OpenDDS with other clients such as Golang, C#, possibly Rust. Have you tried this with a .NET Core approach instead of Windows .NET 4.6?  

I also have OpenDDS running in a container as the runtime only to connect in. So I wanted to have a way to use .NET Core or another language to have containers but not Windows-node-only containers. That is another reason I ask. 

I am going to study what you did here to see what I can get done. But I wanted to ask out loud first.

**Comment by jmmorato** [comment]
Hi @Cingulara 

Theoretically, it should be possible to reference `OpenDDSharp` libraries on `Core 3.1` applications but only for windows platforms. Honestly, I did not test it yet because the time I can spend in the project I'm focus on the `pinvoke` branch.

The goal of the `pinvoke` [branch](https://github.com/jmmorato/openddsharp/tree/pinvoke) is compile `OpenDDSharp` as an `standard2.0` library, compatible with `dotnet core` and multi-platform.

First release will support Windows and Linux platforms and then I'll try to port to Android and iOS. Unfortunately, I cannot give you an ETA for the release because the time I can spend in the project is limited and quite variable during the year, any help would be welcome.

You could estimate the status of the API implementation based on the `Standard.UnitTest` project implemented methods.

**Comment by Cingulara** [comment]
Ok thank you for the quick reply. I am going to study what you did in here and see where I can help. I am wanting to have a Golang interface, C# interface, along w/ the NodeJS one https://github.com/oci-labs/node-opendds I need to test so I have options on using OpenDDS.

I did get OpenDDS to work as a runtime-only inside a container that runs on Linux and Mac and Windows. You have to do net=host unfortunately but it does work. And I have a build container setup so I can build C++ apps inside it and produce artifacts. I want to use other frameworks though and this is a big help.

**Comment by mitza-oci** [comment]
> I am wanting to have a Golang interface, C# interface, along w/ the NodeJS one https://github.com/oci-labs/node-opendds I need to test so I have options on using OpenDDS.

Based on this and https://github.com/oci-labs/opendds-web-monitor/issues/14 I recommend you get in touch with us so we can help you make effective use of OpenDDS in your projects.
https://objectcomputing.com/products/opendds
