### ISSUE TITLE
HelloWorld fails to build

### ISSUE THREAD

**Issue by ww1965** [jmmorato/openddsharp#32]
The 'TestMessageTypeSupportImpl.h' file does not get generated.

**Comment by jmmorato** [comment]
Any other clue would be welcome for the investigation.

Are you creating a new project following the Getting Started documentation or based in the HelloWorld project example from the repository? If using the current project in the repo ensure to pull the 5.0.0 release tag, if based in the Getting Started there is an breaking change in the IDL example that has not been updated yet.

Have you tried to Rebuild instead of just Build the IDL project? Have you tried to manually clean up `bin` and `obj` folders?

If you provide your project attached here, I could take a look by myself.

**Comment by ww1965** [comment]
I am using the code that I downloaded using the zip code option from
GitHub. I have not made any changes to that code at all.

**Comment by ww1965** [comment]
I have tried using Visual Studio 2019 Community version and with Visual
Studio 2019 Professional on two different machines. Both fail to create the
TestMessageTypeSupportImpl.h file so the TestMessageTypeSupport.h file is
filled with errors. The first error is on the #include
“TestMessageTypeSupportImpl.h” line.

**Comment by ww1965** [comment]
I forgot. I did make one change. I had to change the OpenDDSharp version
from 0.5.1 to 0.5.0 since 0.5.1 failed to update from nuget.org.

**Comment by ww1965** [comment]
I pulled the v0.5.0 tag and the demo code compiles and runs.

**Comment by jmmorato** [comment]
Some changes in the generation of the native project makes not easy to downgrade from the **not released** version 0.5.1 to 0.5.0.

I'll remove the NuGet depended projects (HelloWorld and ShapeDemo) from the main repository and create a separated repo for them.

I'm going to close the issue, you can find the HelloWorld working version in https://github.com/jmmorato/openddsharp_helloworld.
