### ISSUE TITLE
Calling Ace.Init() after Ace.Fini() does not initialize

### ISSUE THREAD

**Issue by ww1965** [jmmorato/openddsharp#36]
The flow that is documented in the sample code works fine:

Ace.Init()
... do some messaging
Ace.Fini()

But, if I call Ace.Init() again (without restarting the application), the Ace.Init() call returns 1 (already initialized) but the call to:

ParticipantService.Instance.GetDomainParticipantFactory("-DCPSConfigFile", iniFile);

returns null.

Is this the expected behavior or should the call to Ace.Fini() put DDS into a fully uninitialized state so that Ace.Init() returns a 0 and the call to get the factory return a non-null instance?

**Comment by ww1965** [comment]
actually, the call doesn't return null, but the impl_entity is 0x0000000000000000

**Comment by jmmorato** [comment]
Try to close transport registry before:

```csharp
TransportRegistry.Instance.Release();
TransportRegistry.Close();
ParticipantService.Instance.Shutdown();
```
Fully restarting OpenDDS was not problematic, especially with RTPS transport, few versions ago. I know OpenDDS team has been [working on it](https://github.com/objectcomputing/OpenDDS/blob/dc3262cf16e11bf7594e2cc9354cb395a246b2f0/tests/DCPS/Restart/RestartTest.cpp) and should be possible with the current versions, but not sure in what version was integrated.

I never tested that with OpenDDSharp because the best flow is calling these methods just once in the lifetime of your application. Why do you need the full restart of the library?

In any case, I'm gonna investigate on that and let you know if can be achieved with the current version of OpenDDSharp.

**Comment by ww1965** [comment]
I’ll give that a try.

The code that I am working on allows the user to pick from a number of
transport options (UDP, TCP, DDS, etc.). It is possible (though unlikely)
that they will switch between options during a single execution of the
application. When they switch  between options, I shut down the current
transport and start the new one. When DDS is started a second time, I see
the error. On the second call to Ace.Init() it returns 1 which seems to
indicate that the call to Ace.Fini() did not completely close / shutdown
everything. After the second call to Ace.Init(),
Participant.Instance.IsShutdown is true which causes the call to get the
factory to return an instance that is not usable.

**Comment by jmmorato** [comment]
My advice on that situation would be to keep only one call to `Ace.Init/Fini` and always keep the same factory initialized without config file for the whole application. Then, using `TransportRegistry` configure the transports as your user desires.

You can see some examples on how to configure the transports in the UnitTest project. Check the `TestHelper` class `BindTcp/Udp...` methods.

**Comment by ww1965** [comment]
Thanks. Sounds good.

**Comment by jmmorato** [comment]
I'm closing the ticket, hope the info helped you.

Feel free to reopen it or create a new Discussion.
