### ISSUE TITLE
DataReaderListener question

### ISSUE THREAD

**Issue by ww1965** [jmmorato/openddsharp#37]
Is the expectation that users of OpenDDSharp should write their own implementations of DataReaderListeners? If so, are there are C# examples or some documentation on best practices for the listeners?

**Comment by jmmorato** [comment]
DataReaderListeners, and the rest of entity Listeners, can be used with OpenDDSharp. 

You can read the [OpenDDS developer guide](http://download.objectcomputing.com/OpenDDS/OpenDDS-latest.pdf) and I think is easy to extrapolate to OpenDDSharp (just naming convetion changes).

I have not specific examples but the Unit Tests implemented to ensure the functionality of each entity listener. Take a look to the Listeners folder in the UnitTest project to see a simple implementation.

About best practices... well, for me the best practice is to use WaitSet instead of Listeners always that is possible. With the WaitSet you have more control of the thread where your code is executed. You will have a better throughput but perhaps a little more of latency. 

If you have good reasons to use Listeners instead of WaitSets:
- Do not perform blocking or long processing operations, it could impact the performance of the middleware.
- Do not use locks, because you could easily generate deadlocks when interacting with the middleware locks

**Comment by mitza-oci** [comment]
The following article written by my colleague Tim Pollock may help answer your question

https://objectcomputing.com/resources/publications/sett/october-2020-opendds-in-a-net-application-with-openddsharp

**Comment by jmmorato** [comment]
I'm closing the ticket, hope the info helped you.

Feel free to reopen it or create a new Discussion when needed help.
