### ISSUE TITLE
adding settings for an AnyCPU configuration?

### ISSUE THREAD

**Issue by ww1965** [jmmorato/openddsharp#68]
We would like to see an AnyCPU configuration in the .targets file that maps to x86. This would allow default Visual Studio projects to work with very little configuration changes.  Any possibility of getting that in the next release (or an updated release of the current version?

We have tested it locally by just copying the sections for the x86 configurations and changing the ItemGroup Condition line. 

See complete .targets file attached as a .txt file
[OpenDDSharp.targets.txt](https://github.com/jmmorato/openddsharp/files/7198745/OpenDDSharp.targets.txt)

**Comment by jmmorato** [comment]
The targets you provide contains a solution to copy the native libraries but no for the reference to the OpenDDSharp.dll.

If we try to solve  the OpenDDSharp.dll with the same trick, we will get a mismatch architecture warning when configuring AnyCPU in your C# project. That warning could have real consequences when executing your software depending of your AnyCPU configuration (`prefer 32-bit` checkbox selected or not).

The same trick for the OpenDDSharp.dll, could be applied to the OpenDDSharp.Standard branch and avoid the platform mismatch but I discarded the idea of AnyCPU because in dotnet core is common to compile the application per runtime identifier (win-x64, win-x86, linux-x64...), so for me AnyCPU make no sense anymore inside the dotnet core world.
