### ISSUE TITLE
How to detect a deleted instance as deleted by the datawriter?

### ISSUE THREAD

**Issue by Brotbeck** [jmmorato/openddsharp#8]
Maybe the solution I chose is based on a wrong understanding of OpenDDS 
I try to explain my use case for better understanding my problem:

I read  RFID tags from a reader and publish them to OpenDDS.
The RFIDreader is a Gate that means:

- first time read => the tag enters a room
- Second time read => the tag leaves the room 

the tag-id is the key  of the datatype of topic room

- entering the room  creates an instance of the topic’s datatype
- leaving the room deletes the instance

Every subscriber can read all instances of topic room multiple times and therefore know which tags are in the room if I set instanceMask to AliveInstanceState. 

If the RFID Reader reads a tag the datawriter creates a new instance if no instance with this key exists otherwise it removes the instance with this key.

The problem
The subscriber can read the tags as expected but the writer cannot detect whether an instance is deleted or not. Therefore a reentering of a tag in the room is not possible since the instance still exists even if it is marked as deleted.

**Comment by jmmorato** [comment]
Not sure if I understood correctly the situation.

You said that you read with AliveInstanceState, so only the alive instances are read. If you found the tag in the list of samples received you Delete with the writer, if not, you Write again. Like that you don't care if it is a first entering or a reentering.

 _since the instance still exists even if it is marked as deleted._

That is a confusing for me, I'm not sure what you meant exactly. You should not care about that because you are reading only AliveInstances. In any case, if you want to purge deleted instances you should use:

```
            dataReaderQos.ReaderDataLifecycle.AutopurgeDisposedSamplesDelay = new Duration
            {
                Seconds = Duration.ZeroSeconds,
                NanoSeconds = Duration.ZeroNanoseconds
            };
```
